git:
  depth: 3

sudo: false
language: cpp
os: linux
dist: trusty
addons:
  apt:
    sources: &core_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
      - llvm-toolchain-trusty-5.0
    packages:
      - clang-3.6
      - clang-3.8
      - clang-4.0
      - clang-5.0
      - lib32stdc++6
      - lib32z1-dev
      - libc6-dev-i386
      - linux-libc-dev
      - g++-4.8
      - g++-4.9
      - g++-5
      - g++-6
      - g++-7
      - g++-multilib
      - g++-4.8-multilib
      - g++-4.9-multilib
      - g++-5-multilib
      - g++-6-multilib
      - g++-7-multilib
    cache:
      directories:
        - ../mysql-5.0
env:
 - MATRIX_EVAL="CC=clang-3.6 && CXX=clang++-3.6"
 - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
 - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
 - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
 - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

 - MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
 - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
 - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
 - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
 - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

matrix:
  fast_finish: true
  allow_failures:
    - env: MATRIX_EVAL="CC=clang-3.7 && CXX=clang++-3.7"
    - env: MATRIX_EVAL="CC=clang-3.9 && CXX=clang++-3.9"
    - env: MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
    - env: MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - env: MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_script:
  - CHECKOUT_DIR=$PWD && cd .. && $CHECKOUT_DIR/tools/checkout-deps.sh && cd $CHECKOUT_DIR
script:
  - mkdir build && cd build
  - PATH="~/.local/bin:$PATH"
  - eval "${MATRIX_EVAL}"
  - python ../configure.py --enable-optimize --sdks=episode1,tf2,l4d2,csgo,dota
  - ambuild
